#pragma once

using MouseButton = enum MouseButton
{
	SIBOX_MOUSE_BUTTON_NONE   = 0,
	SIBOX_MOUSE_BUTTON_LEFT   = 1,
	SIBOX_MOUSE_BUTTON_MIDDLE = 2,
	SIBOX_MOUSE_BUTTON_RIGHT  = 3,
	SIBOX_MOUSE_BUTTON_4      = 4,
	SIBOX_MOUSE_BUTTON_5      = 5,
	SIBOX_MOUSE_BUTTON_6      = 6,
	SIBOX_MOUSE_BUTTON_7      = 7,
	SIBOX_MOUSE_BUTTON_8      = 8,
	SIBOX_MOUSE_BUTTON_COUNT  = SIBOX_MOUSE_BUTTON_8,
};

NODISCARD const char* MouseButtonToString(MouseButton button);
